accounts:
  - name: khanh
    coins: ["200000000000anone"]
  - name: hung
    coins: ["10000anone"]
  - name: minh
    coins: ["100anone"]
  - name: vinh
    coins: ["1anone"]
  - name: jacob
    coins: ["1000000000000anone"]
validator:
  name: khanh
  staked: "100000000000anone"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
genesis:
  chain_id: "anone-testnet-1"
  app_state:
    staking:
      params:
        bond_denom: "anone"
    mint:
      params:
        mint_denom: "anone"
    gov:
      deposit_params:
        min_deposit:
          denom: "anone"
    crisis:
      constant_fee:
        denom: "anone"
